main:
  - name: 新闻
    url: post
    weight: 20
  - name: 成员
    weight: 30
  - name: 当前成员
    pageRef: people
    parent: 成员
    weight: 1
  - name: 毕业生
    url: alumni
    weight: 2
    parent: 成员
  - name: 活动
    url: event
    weight: 50
  - name: 科研
    weight: 40
  - name: 出版物
    url: publication
    weight: 1
    parent: 科研
  - name: 毕业论文
    url: thesis
    weight: 2
    parent: 科研
  - name: 获奖
    url: honor
    weight: 3
    parent: 科研
  - name: 项目
    url: projects
    weight: 4
    parent: 科研
  - name: 专利
    url: patents
    weight: 5
    parent: 科研
  - name: 软著
    url: software_copyrights
    weight: 6
    parent: 科研  
  - name: 联系我们
    url: contact
    weight: 60
  - name: 成员登录
    url: /admin/
    weight: 70
    params:
      root: true
