# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  
  - name: News
    url: post
    weight: 20
  - name: People
    weight: 30
  - name: Current People
    pageRef: people
    parent: People
    weight: 1
  - name: Alumni
    url: alumni
    weight: 2
    parent: People
  - name: Research
    weight: 40
  - name: Publication
    url: publication
    weight: 1
    parent: Research
  - name: Thesis
    url: thesis
    weight: 2
    parent: Research
  - name: Honor
    url: honor
    weight: 3
    parent: Research
  - name: Projects
    url: projects
    weight: 4
    parent: Research
  - name: Patents
    url: patents
    weight: 5
    parent: Research
  - name: Software copyrights
    url: software_copyrights
    weight: 6
    parent: Research 
  - name: Events
    url: event
    weight: 40
  - name: Contact
    url: contact
    weight: 60
  - name: Member Login
    url: /admin/
    weight: 70
