############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/gzu-ai/hugo-blox-builder/modules/blox-krrbootstrap
  # - path: F:\MyGit\hugo-blox-builder-main\hugo-blox-builder-main\modules\blox-krrbootstrap
  - path: github.com/gzu-ai/hugo-blox-builder/modules/blox-seo
  - path: vendor